const DIVISIONS = [
  { division: "011B1", name: "Oceania East Women's B1" },
  { division: "011C1", name: "Oceania East Women's C1" },
  { division: "011D1", name: "Oceania East Women's D1" },
  { division: "031A1", name: "EMEAE East Women's A1" },
  { division: "031B1", name: "EMEAE East Women's B1" },
  { division: "031B2", name: "EMEAE East Women's B2" },
  { division: "031C1", name: "EMEAE East Women's C1" },
  { division: "031C2", name: "EMEAE East Women's C2" },
  { division: "031C3", name: "EMEAE East Women's C3" },
  { division: "031D1", name: "EMEAE East Women's D1" },
  { division: "035A1", name: "EMEAE Central Women's A1" },
  { division: "035B1", name: "EMEAE Central Women's B1" },
  { division: "035C1", name: "EMEAE Central Women's C1" },
  { division: "035C2", name: "EMEAE Central Women's C2" },
  { division: "035D1", name: "EMEAE Central Women's D1" },
  { division: "039B1", name: "EMEAE West Women's B1" },
  { division: "039C1", name: "EMEAE West Women's C1" },
  { division: "039D1", name: "EMEAE West Women's D1" },
  { division: "061A1", name: "Americas East Women's A1" },
  { division: "061B1", name: "Americas East Women's B1" },
  { division: "061B2", name: "Americas East Women's B2" },
  { division: "061C1", name: "Americas East Women's C1" },
  { division: "061C2", name: "Americas East Women's C2" },
  { division: "061D1", name: "Americas East Women's D1" },
  { division: "061D2", name: "Americas East Women's D2" },
  { division: "069B1", name: "Americas West Women's B1" },
  { division: "069C1", name: "Americas West Women's C1" },
  { division: "211A1", name: "Oceania East Open A1" },
  { division: "211B1", name: "Oceania East Open B1" },
  { division: "211C1", name: "Oceania East Open C1" },
  { division: "219A1", name: "Oceania West Open A1" },
  { division: "219B1", name: "Oceania West Open B1" },
  { division: "219B2", name: "Oceania West Open B2" },
  { division: "219C1", name: "Oceania West Open C1" },
  { division: "219C2", name: "Oceania West Open C2" },
  { division: "219D1", name: "Oceania West Open D1" },
  { division: "221A1", name: "Asia East Open A1" },
  { division: "221B1", name: "Asia East Open B1" },
  { division: "221C1", name: "Asia East Open C1" },
  { division: "221D1", name: "Asia East Open D1" },
  { division: "231A1", name: "EMEAE East Open A1" },
  { division: "231A2", name: "EMEAE East Open A2" },
  { division: "231B1", name: "EMEAE East Open B1" },
  { division: "231B2", name: "EMEAE East Open B2" },
  { division: "231C1", name: "EMEAE East Open C1" },
  { division: "232A1", name: "EMEAE North-East Open A1" },
  { division: "232A2", name: "EMEAE North-East Open A2" },
  { division: "232B1", name: "EMEAE North-East Open B1" },
  { division: "232B2", name: "EMEAE North-East Open B2" },
  { division: "232B3", name: "EMEAE North-East Open B3" },
  { division: "232C1", name: "EMEAE North-East Open C1" },
  { division: "232C2", name: "EMEAE North-East Open C2" },
  { division: "232C3", name: "EMEAE North-East Open C3" },
  { division: "232D1", name: "EMEAE North-East Open D1" },
  { division: "233A1", name: "EMEAE South Open A1" },
  { division: "233B1", name: "EMEAE South Open B1" },
  { division: "233B2", name: "EMEAE South Open B2" },
  { division: "233C1", name: "EMEAE South Open C1" },
  { division: "235A1", name: "EMEAE Central Open A1" },
  { division: "235A2", name: "EMEAE Central Open A2" },
  { division: "235A3", name: "EMEAE Central Open A3" },
  { division: "235B1", name: "EMEAE Central Open B1" },
  { division: "235B2", name: "EMEAE Central Open B2" },
  { division: "235B3", name: "EMEAE Central Open B3" },
  { division: "235B4", name: "EMEAE Central Open B4" },
  { division: "235C1", name: "EMEAE Central Open C1" },
  { division: "235C2", name: "EMEAE Central Open C2" },
  { division: "235C3", name: "EMEAE Central Open C3" },
  { division: "235D1", name: "EMEAE Central Open D1" },
  { division: "237A1", name: "EMEAE North Open A1" },
  { division: "237A2", name: "EMEAE North Open A2" },
  { division: "237B1", name: "EMEAE North Open B1" },
  { division: "237B2", name: "EMEAE North Open B2" },
  { division: "237B3", name: "EMEAE North Open B3" },
  { division: "237B4", name: "EMEAE North Open B4" },
  { division: "237C1", name: "EMEAE North Open C1" },
  { division: "237C2", name: "EMEAE North Open C2" },
  { division: "237C3", name: "EMEAE North Open C3" },
  { division: "237D1", name: "EMEAE North Open D1" },
  { division: "239A1", name: "EMEAE West Open A1" },
  { division: "239A2", name: "EMEAE West Open A2" },
  { division: "239B1", name: "EMEAE West Open B1" },
  { division: "239B2", name: "EMEAE West Open B2" },
  { division: "239B3", name: "EMEAE West Open B3" },
  { division: "239C1", name: "EMEAE West Open C1" },
  { division: "239C2", name: "EMEAE West Open C2" },
  { division: "239C3", name: "EMEAE West Open C3" },
  { division: "241A1", name: "EMEAW East Open A1" },
  { division: "241A2", name: "EMEAW East Open A2" },
  { division: "241B1", name: "EMEAW East Open B1" },
  { division: "241B2", name: "EMEAW East Open B2" },
  { division: "241B3", name: "EMEAW East Open B3" },
  { division: "241B4", name: "EMEAW East Open B4" },
  { division: "241B5", name: "EMEAW East Open B5" },
  { division: "241C1", name: "EMEAW East Open C1" },
  { division: "241C2", name: "EMEAW East Open C2" },
  { division: "241C3", name: "EMEAW East Open C3" },
  { division: "241D1", name: "EMEAW East Open D1" },
  { division: "241D2", name: "EMEAW East Open D2" },
  { division: "243A1", name: "EMEAW South Open A1" },
  { division: "243A2", name: "EMEAW South Open A2" },
  { division: "243B1", name: "EMEAW South Open B1" },
  { division: "243B2", name: "EMEAW South Open B2" },
  { division: "243B3", name: "EMEAW South Open B3" },
  { division: "243B4", name: "EMEAW South Open B4" },
  { division: "243C1", name: "EMEAW South Open C1" },
  { division: "243C2", name: "EMEAW South Open C2" },
  { division: "243C3", name: "EMEAW South Open C3" },
  { division: "245A1", name: "EMEAW Central Open A1" },
  { division: "245A2", name: "EMEAW Central Open A2" },
  { division: "245B1", name: "EMEAW Central Open B1" },
  { division: "245B2", name: "EMEAW Central Open B2" },
  { division: "245B3", name: "EMEAW Central Open B3" },
  { division: "245B4", name: "EMEAW Central Open B4" },
  { division: "245C1", name: "EMEAW Central Open C1" },
  { division: "245C2", name: "EMEAW Central Open C2" },
  { division: "245C3", name: "EMEAW Central Open C3" },
  { division: "245D1", name: "EMEAW Central Open D1" },
  { division: "245D2", name: "EMEAW Central Open D2" },
  { division: "247A1", name: "EMEAW North Open A1" },
  { division: "247B1", name: "EMEAW North Open B1" },
  { division: "247B2", name: "EMEAW North Open B2" },
  { division: "247B3", name: "EMEAW North Open B3" },
  { division: "247C1", name: "EMEAW North Open C1" },
  { division: "247C2", name: "EMEAW North Open C2" },
  { division: "249A1", name: "EMEAW West Open A1" },
  { division: "249A2", name: "EMEAW West Open A2" },
  { division: "249B1", name: "EMEAW West Open B1" },
  { division: "249B2", name: "EMEAW West Open B2" },
  { division: "249B3", name: "EMEAW West Open B3" },
  { division: "249C1", name: "EMEAW West Open C1" },
  { division: "249C2", name: "EMEAW West Open C2" },
  { division: "249C3", name: "EMEAW West Open C3" },
  { division: "251A1", name: "S America East Open A1" },
  { division: "251B1", name: "S America East Open B1" },
  { division: "251C1", name: "S America East Open C1" },
  { division: "251D1", name: "S America East Open D1" },
  { division: "261A1", name: "Americas East Open A1" },
  { division: "261A2", name: "Americas East Open A2" },
  { division: "261B1", name: "Americas East Open B1" },
  { division: "261B2", name: "Americas East Open B2" },
  { division: "261B3", name: "Americas East Open B3" },
  { division: "261B4", name: "Americas East Open B4" },
  { division: "261C1", name: "Americas East Open C1" },
  { division: "261C2", name: "Americas East Open C2" },
  { division: "261C3", name: "Americas East Open C3" },
  { division: "261D1", name: "Americas East Open D1" },
  { division: "261D2", name: "Americas East Open D2" },
  { division: "265A1", name: "Americas Central Open A1" },
  { division: "265B1", name: "Americas Central Open B1" },
  { division: "265B2", name: "Americas Central Open B2" },
  { division: "265B3", name: "Americas Central Open B3" },
  { division: "265C1", name: "Americas Central Open C1" },
  { division: "265C2", name: "Americas Central Open C2" },
  { division: "265C3", name: "Americas Central Open C3" },
  { division: "265D1", name: "Americas Central Open D1" },
  { division: "269A1", name: "Americas West Open A1" },
  { division: "269B1", name: "Americas West Open B1" },
  { division: "269B2", name: "Americas West Open B2" },
  { division: "269B3", name: "Americas West Open B3" },
  { division: "269C1", name: "Americas West Open C1" },
  { division: "269C2", name: "Americas West Open C2" },
  { division: "269D1", name: "Americas West Open D1" },
  { division: "271A1", name: "Atlantic East Open A1" },
  { division: "271A2", name: "Atlantic East Open A2" },
  { division: "271B1", name: "Atlantic East Open B1" },
  { division: "271B2", name: "Atlantic East Open B2" },
  { division: "271C1", name: "Atlantic East Open C1" },
  { division: "271D1", name: "Atlantic East Open D1" },
  { division: "275A1", name: "Atlantic Central Open A1" },
  { division: "275B1", name: "Atlantic Central Open B1" },
  { division: "275C1", name: "Atlantic Central Open C1" },
  { division: "279A1", name: "Atlantic West Open A1" },
];

export const getDivisions = () =>
  DIVISIONS.map(({ division, name }) => {
    const race = name
      .replace(" Women's", "")
      .replace(" (Men's/Mixed)", "")
      .replace(" Division", "")
      .replace(" - ", " ");
    const parts = race.split(" ");
    const cat = parts[parts.length - 1][0];

    return {
      div: division,
      name,
      region: parts[0],
      cat,
      mix: name.indexOf("(Women's)") > -1 ? "W" : "M",
    };
  });

export default DIVISIONS;
